[package]
name = "crabcan"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
nix = "0.22.1"
scan_fmt = "0.2.6"
